name: op-docs

services:
  postgresql:
    networks:
      - internal
    ports: !override
      - "5435:5432"

  redis:
    networks:
      - internal

  mailcatcher:
    ports: !reset []

  minio:
    networks:
      - internal
    ports: !reset []

  createbuckets:
    networks:
      - internal

  app-dev:
    networks:
      - internal
      - external
    environment:
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - DJANGO_CSRF_TRUSTED_ORIGINS=https://docs.local
      - DJANGO_PATH_PREFIX=/backend
      - OIDC_STORE_ACCESS_TOKEN=true
      - OIDC_RP_SCOPES=openid api_v3 profile email
      - OPEN_PROJECT_HOST=https://openproject.local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docs-backend.rule=Host(`docs.local`) && PathPrefix(`/backend`)"
      - "traefik.http.routers.docs-backend.entrypoints=websecure"
      - "traefik.http.services.docs-backend.loadbalancer.server.port=8000"
      - "traefik.http.routers.docs-backend.middlewares=backend-strip"
      - "traefik.http.middlewares.backend-strip.stripprefix.prefixes=/backend"
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    ports: !reset []

  celery-dev:
    networks:
      - internal

  nginx:
    networks:
      - internal
    ports: !reset []
    depends_on: !override
      app-dev:
        condition: service_started
      y-provider:
        condition: service_started

  frontend:
    ports: !reset []

  frontend-development:
    user: "${DOCKER_USER:-1000}"
    networks:
      - internal
      - external
    environment:
      - NEXT_PUBLIC_API_ORIGIN=https://docs.local/backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docs.rule=Host(`docs.local`)"
      - "traefik.http.routers.docs.entrypoints=websecure"
    build:
      context: .
      dockerfile: ./src/frontend/Dockerfile
      target: impress-dev
    image: impress:frontend-development
    volumes:
      - ./src/frontend:/home/frontend

  y-provider:
    networks:
      - internal
    ports: !reset []

networks:
  internal:
  external:
    name: gateway
    external: true
